repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-executables-have-shebangs

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: local
    hooks:
      - id: check-private-data
        name: Check for private data
        entry: python
        language: system
        args: ["-c", "
import sys;
import re;
content = open(sys.argv[1]).read();
patterns = [
  r'E4:B3:23:5B:F5:76',
  r'4a942a522abf710b3c8e61973e3aa17a',
  r'45b31b6c213dfcc16059010bb107746aa4dbb51589e9192e',
  r'192\.168\.10\.10',
  r'mqttuser',
  r'mqttpass'
];
for pattern in patterns:
  if re.search(pattern, content, re.IGNORECASE):
    print(f'PRIVATE DATA DETECTED: {pattern}');
    sys.exit(1)
        "]
        files: \.(py|json|yaml|yml|env|md)$
        exclude: ^(.*\.example|.*\.md|tools/.*\.py)$